/*
 * QuickChart API
 * An API to generate charts and QR codes using QuickChart services.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChartPostRequest
 */
public class ChartPostRequestTest {
    private final ChartPostRequest model = new ChartPostRequest();

    /**
     * Model tests for ChartPostRequest
     */
    @Test
    public void testChartPostRequest() {
        // TODO: test ChartPostRequest
    }

    /**
     * Test the property 'backgroundColor'
     */
    @Test
    public void backgroundColorTest() {
        // TODO: test backgroundColor
    }

    /**
     * Test the property 'chart'
     */
    @Test
    public void chartTest() {
        // TODO: test chart
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

}
